[versions]
kotlin = "1.8.22"
dokka = "1.8.20"
coroutines = "1.7.2"
paper = "1.18"

[libraries]
paper = "io.papermc.paper:paper-api:1.18-R0.1-SNAPSHOT"
coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}

[plugins]
kotlin = {id = "org.jetbrains.kotlin.jvm", version.ref="kotlin"}
dokka = {id = "org.jetbrains.dokka", version.ref="dokka"}